---
driver:
  name: vagrant
  network:
  - ["private_network", { type: "dhcp" }]
provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
    driver:
      customize:
        memory: 512

suites:
  - name: default
    run_list:
      - recipe[jira_server02::default]
    attributes:
